/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  plugins: [require("tailwind-scrollbar")],
  theme: {
    fontFamily: {
      merinda: ["Merienda, serif, system-ui"],
    },
    colors: {
      "howler-accent": "#3A3120",
      "hogwarts-accent": "#FAECBF",
      "hogwarts-light": "#392A48",
      "hogwarts-dark": "#2F223A",
      "gryffindor-accent": "#BDAC5C",
      "gryffindor-light": "#A62025",
      "gryffindor-dark": "#5D070A",
      "slytherin-accent": "#939393",
      "slytherin-light": "#214926",
      "slytherin-dark": "#112D14",
      "hufflepuff-accent": "#363430",
      "hufflepuff-light": "#D9AB0D",
      "hufflepuff-dark": "#A17F0B",
      "ravenclaw-accent": "#946B2D",
      "ravenclaw-light": "#02223B",
      "ravenclaw-dark": "#01121E",
    },
    extend: {},
  },
  safelist: [
    "howler-accent",
    "border-hogwarts-accent",
    "fill-hogwarts-accent",
    "text-hogwarts-accent",
    "text-hogwarts-dark",
    "bg-hogwarts-accent",
    "bg-hogwarts-light",
    "bg-hogwarts-dark",
    "border-gryffindor-accent",
    "fill-gryffindor-accent",
    "text-gryffindor-accent",
    "text-gryffindor-dark",
    "bg-gryffindor-accent",
    "bg-gryffindor-light",
    "bg-gryffindor-dark",
    "border-slytherin-accent",
    "fill-slytherin-accent",
    "text-slytherin-accent",
    "text-slytherin-dark",
    "bg-slytherin-accent",
    "bg-slytherin-light",
    "bg-slytherin-dark",
    "border-hufflepuff-accent",
    "fill-hufflepuff-accent",
    "text-hufflepuff-accent",
    "text-hufflepuff-dark",
    "bg-hufflepuff-accent",
    "bg-hufflepuff-light",
    "bg-hufflepuff-dark",
    "border-ravenclaw-accent",
    "fill-ravenclaw-accent",
    "text-ravenclaw-accent",
    "text-ravenclaw-dark",
    "bg-ravenclaw-accent",
    "bg-ravenclaw-light",
    "bg-ravenclaw-dark",
  ],
};
